stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  DB_HOST: mysql
  DB_PORT: 3306
  DB_NAME: test_db
  DB_USER: test_user
  DB_PASSWORD: test_password

build_frontend:
  stage: build
  image: node:16
  script:
    - cd src/main/java/com/group2/Tiger_Talks/frontend/build/
    - npm install
    - npm run build
  artifacts:
    paths:
      - src/main/java/com/group2/Tiger_Talks/frontend/build/


build_backend:
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - src/main/java/com/group2/Tiger_Talks/backend/target/*.jar

test_backend:
  stage: test
  image: maven:3.8.4-openjdk-17
  services:
    - name: mysql:8.0
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: $DB_NAME
    MYSQL_USER: $DB_USER
    MYSQL_PASSWORD: $DB_PASSWORD
  script:
    - mvn $MAVEN_CLI_OPTS test
  dependencies:
    - build_backend
